# Generated by Django 6.1.1 on 2026-09-14 23:23

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('lojas', '0002_loja_codigo'),
        ('produtos', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='VendaItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('codigo_erp', models.CharField(db_index=True, max_length=20)),
                ('descricao', models.CharField(blank=True, max_length=250)),
                ('ano_mes', models.CharField(db_index=True, max_length=7)),
                ('itens', models.DecimalField(decimal_places=3, default=0, max_digits=12)),
                ('venda', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('desconto', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('custo', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('lucro', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('loja', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='vendas', to='lojas.loja')),
                ('produto', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='vendas', to='produtos.produto')),
            ],
            options={
                'verbose_name': 'Venda de item',
                'verbose_name_plural': 'Vendas de item',
                'indexes': [models.Index(fields=['ano_mes', 'loja'], name='vendas_vend_ano_mes_a1c43e_idx')],
                'constraints': [models.UniqueConstraint(fields=('loja', 'codigo_erp', 'ano_mes'), name='uniq_venda_item')],
            },
        ),
    ]
