# Generated by Django 6.1.1 on 2026-09-17 12:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vendas', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='SelecaoItemRelevante',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ean', models.CharField(db_index=True, max_length=20, unique=True)),
                ('selecionado', models.BooleanField(default=True)),
                ('atualizado_em', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Seleção de item relevante',
                'verbose_name_plural': 'Seleções de itens relevantes',
            },
        ),
    ]
