# Generated by Django 6.1.1 on 2026-09-19 14:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vendas', '0002_selecaoitemrelevante'),
    ]

    operations = [
        migrations.CreateModel(
            name='AjusteItemMonitoramentoDiario',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ean', models.CharField(db_index=True, max_length=20)),
                ('tipo', models.CharField(choices=[('EXCLUIR', 'Excluir'), ('INCLUIR', 'Incluir')], max_length=10)),
                ('categoria', models.CharField(blank=True, help_text="Obrigatório pra INCLUIR (nome exato da categoria, ex. 'Propagado'). Ignorado em EXCLUIR.", max_length=40)),
                ('observacao', models.CharField(blank=True, max_length=200)),
                ('ativo', models.BooleanField(default=True)),
                ('criado_em', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'Ajuste manual (monitoramento diário)',
                'verbose_name_plural': 'Ajustes manuais (monitoramento diário)',
            },
        ),
    ]
