# Generated by Django 6.1.1 on 2026-09-14 22:37

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Loja',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=50, unique=True)),
                ('bandeira', models.CharField(blank=True, max_length=30)),
                ('cidade', models.CharField(blank=True, max_length=60)),
                ('bairro', models.CharField(blank=True, max_length=120)),
                ('zona', models.CharField(blank=True, max_length=30)),
                ('endereco', models.CharField(blank=True, max_length=200)),
                ('razao_social', models.CharField(blank=True, max_length=200)),
                ('lat', models.FloatField(blank=True, null=True)),
                ('lon', models.FloatField(blank=True, null=True)),
            ],
            options={
                'verbose_name': 'Loja',
                'verbose_name_plural': 'Lojas',
                'ordering': ['nome'],
            },
        ),
    ]
