# Generated by Django 6.1.1 on 2026-09-14 23:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lojas', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='loja',
            name='codigo',
            field=models.CharField(blank=True, db_index=True, help_text="Código da unidade de negócio no ERP (ex.: '02'), extraído do nome 'Loja N' -- é como o relatório de vendas identifica a loja ('Cód. Un. Neg.').", max_length=10),
        ),
    ]
