# Generated by Django 6.1.1 on 2026-09-15 11:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lojas', '0002_loja_codigo'),
    ]

    operations = [
        migrations.AddField(
            model_name='loja',
            name='ativa',
            field=models.BooleanField(default=True, help_text='False para loja fechada (ex.: Loja 12/Jaguaquara, fechada -- confirmado pelo Gabriel em 2026-09-15). Mantida no cadastro por causa do histórico de vendas, mas fora das telas ao vivo.'),
        ),
    ]
