# Generated by Django 6.1.1 on 2026-09-14 23:23

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Produto',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ean', models.CharField(blank=True, db_index=True, max_length=20)),
                ('etiqueta', models.CharField(blank=True, db_index=True, max_length=20)),
                ('descricao', models.CharField(blank=True, max_length=250)),
                ('fabricante', models.CharField(blank=True, max_length=120)),
                ('classificacao_completa', models.CharField(blank=True, max_length=250)),
                ('classificacao', models.CharField(blank=True, db_index=True, max_length=120)),
                ('curva_valor', models.CharField(blank=True, max_length=2)),
                ('curva_qtd', models.CharField(blank=True, max_length=2)),
                ('preco_venda_atual', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('preco_referencial', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
            ],
            options={
                'verbose_name': 'Produto',
                'verbose_name_plural': 'Produtos',
                'ordering': ['descricao'],
            },
        ),
    ]
