# Generated by Django 6.1.1 on 2026-09-15 17:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('produtos', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='produto',
            name='subclassificacao',
            field=models.CharField(blank=True, db_index=True, help_text="3º nível da árvore ('ARVORE NOVA > classificacao > subclassificacao'), quando existir -- nem todo produto tem esse nível.", max_length=120),
        ),
    ]
