"""
Django settings for config project.

Generated by 'django-admin startproject' using Django 6.1.1.

For more information on this file, see
https://docs.djangoproject.com/en/6.1/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/6.1/ref/settings/
"""

from pathlib import Path

# Build paths inside the project like this: BASE_DIR / 'subdir'.
BASE_DIR = Path(__file__).resolve().parent.parent


# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/6.1/howto/deployment/checklist/

# SECURITY WARNING: keep the secret key used in production secret!
SECRET_KEY = 'django-insecure-0-c$*&rxet&ka-e18vx8zsk$kj)gb4s^eak4nj5tbt!+f#e#ye'

# SECURITY WARNING: don't run with debug turned on in production!
DEBUG = False

# IP do PC do Gabriel na rede do escritório — outras pessoas acessam por
# http://192.168.100.74:8000/. Já mudou uma vez (roteador reatribuiu via
# DHCP, 17/09/26: era 192.168.0.33) -- se parar de funcionar de novo,
# rodar `ipconfig` e atualizar aqui. Vale reservar esse IP no roteador
# pra não quebrar de novo (oferecido a Gabriel, sem decisão ainda).
ALLOWED_HOSTS = ['192.168.100.74', 'localhost', '127.0.0.1']


# Application definition

INSTALLED_APPS = [
    'django.contrib.admin',
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    'django.contrib.staticfiles',
    'apps.lojas',
    'apps.captacao',
    'apps.produtos',
    'apps.vendas',
    'apps.monitor',
]

MIDDLEWARE = [
    'django.middleware.security.SecurityMiddleware',
    'django.contrib.sessions.middleware.SessionMiddleware',
    'django.middleware.common.CommonMiddleware',
    'django.middleware.csrf.CsrfViewMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    'django.contrib.messages.middleware.MessageMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',
]

ROOT_URLCONF = 'config.urls'

TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        'DIRS': [],
        'APP_DIRS': True,
        'DIRS': [BASE_DIR / 'templates'],
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.request',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',
            ],
        },
    },
]

WSGI_APPLICATION = 'config.wsgi.application'


# Database
# https://docs.djangoproject.com/en/6.1/ref/settings/#databases

DATABASES = {
    'default': {
        'ENGINE': 'django.db.backends.sqlite3',
        'NAME': BASE_DIR / 'db.sqlite3',
        # timeout maior (padrão do driver é 5s) -- SQLite só permite 1
        # escritor por vez; com o servidor rodando e comandos manage.py
        # avulsos (sincronizar_captacao, exportar_itens_relevantes) às
        # vezes escrevendo ao mesmo tempo, um "database is locked"
        # transitório vira erro 500 em vez de só esperar a vez.
        'OPTIONS': {'timeout': 20},
    }
}


# Password validation
# https://docs.djangoproject.com/en/6.1/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    {
        'NAME': 'django.contrib.auth.password_validation.UserAttributeSimilarityValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.MinimumLengthValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.CommonPasswordValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.NumericPasswordValidator',
    },
]


# Internationalization
# https://docs.djangoproject.com/en/6.1/topics/i18n/

LANGUAGE_CODE = 'pt-br'

TIME_ZONE = 'America/Recife'

USE_I18N = True

# Sem isso, floatformat/número em template ignora o locale pt-br e sai
# sem separador de milhar ("16036112.48" em vez de "16.036.112,48") --
# achado do Gabriel vendo as tabelas de Custo x Margem/Relevância.
USE_THOUSAND_SEPARATOR = True

USE_TZ = True


# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/6.1/howto/static-files/

STATIC_URL = 'static/'
STATICFILES_DIRS = [BASE_DIR / 'static']


# Email
# https://docs.djangoproject.com/en/6.1/topics/email/#topic-email-configuration

MAILERS = {
    'default': {
        'BACKEND': 'django.core.mail.backends.console.EmailBackend',
    },
}


# --- Config própria do projeto -------------------------------------------

# Caixa de entrada de dados (planilhas do robô/ERP que o Gabriel joga aqui
# pra importar via manage.py importar_*). Gitignored.
DADOS_ENTRADA = BASE_DIR / 'dados' / 'entrada'

# Caminho do banco sqlite do robo_cotacao (projeto separado, com git
# próprio) -- lido em modo somente-leitura por `captacao.sincronizar`, não
# é uma dependência de runtime (se o caminho não existir, o comando avisa
# e não quebra o painel). Ajustar aqui se o robô mudar de máquina/pasta.
CAMINHO_DB_ROBO_COTACAO = (
    BASE_DIR.parent.parent / 'robo_cotacao' / '_precos_continuos.sqlite3'
)

# Onde `exportar_itens_relevantes` grava a lista de EANs prioritários pro
# robô ler (`termos_prioritarios.py` do lado de lá) -- mesmo padrão de
# arquivo compartilhado entre os dois projetos que lojas_config.json/
# concorrentes_config.json já usam.
CAMINHO_ITENS_RELEVANTES_ROBO_COTACAO = (
    BASE_DIR.parent.parent / 'robo_cotacao' / '_itens_relevantes.json'
)
