# Generated by Django 6.1.1 on 2026-09-14 22:37

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Rede',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=60, unique=True)),
                ('tipo', models.CharField(choices=[('nossa', 'Nossa bandeira'), ('concorrente', 'Concorrente')], default='concorrente', max_length=20)),
                ('substrings', models.JSONField(default=list, help_text='Trechos (case-insensitive) que casam contra o nome bruto do estabelecimento.')),
            ],
            options={
                'verbose_name': 'Rede',
                'verbose_name_plural': 'Redes',
                'ordering': ['tipo', 'nome'],
            },
        ),
        migrations.CreateModel(
            name='PrecoCaptado',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ean', models.CharField(db_index=True, max_length=20)),
                ('estabelecimento', models.CharField(max_length=200)),
                ('endereco', models.CharField(max_length=300)),
                ('titulo', models.CharField(blank=True, max_length=300)),
                ('preco', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('distancia', models.CharField(blank=True, max_length=30)),
                ('termo_origem', models.CharField(blank=True, max_length=120)),
                ('cidade_busca', models.CharField(blank=True, db_index=True, max_length=60)),
                ('atualizado_em', models.DateTimeField()),
                ('rede', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='precos', to='captacao.rede')),
            ],
            options={
                'verbose_name': 'Preço captado',
                'verbose_name_plural': 'Preços captados',
                'indexes': [models.Index(fields=['ean', 'cidade_busca'], name='captacao_pr_ean_33fa37_idx')],
                'constraints': [models.UniqueConstraint(fields=('ean', 'estabelecimento', 'endereco'), name='uniq_preco_captado')],
            },
        ),
    ]
