# Generated by Django 6.1.1 on 2026-09-15 17:20

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('captacao', '0001_initial'),
        ('lojas', '0003_loja_ativa'),
    ]

    operations = [
        migrations.AddField(
            model_name='precocaptado',
            name='lat',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='precocaptado',
            name='loja',
            field=models.ForeignKey(blank=True, help_text="Só preenchido pra registros de rede='nossa' -- o robô não distingue qual loja física é qual, então isso é vinculado depois por heurística de endereço (número da rua) em 'manage.py vincular_lojas_captacao', não pelo robô.", null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='precos_captados', to='lojas.loja'),
        ),
        migrations.AddField(
            model_name='precocaptado',
            name='lon',
            field=models.FloatField(blank=True, null=True),
        ),
    ]
