# Generated by Django 6.1.1 on 2026-09-15 17:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('captacao', '0002_precocaptado_lat_precocaptado_loja_precocaptado_lon'),
    ]

    operations = [
        migrations.AddField(
            model_name='precocaptado',
            name='bairro',
            field=models.CharField(blank=True, db_index=True, help_text="Extraído do endereço bruto (regex, não vem separado do robô) via 'manage.py extrair_bairros_captacao' -- pedido do Gabriel pra comparar preço do mesmo produto entre bairros da mesma cidade (ex.: bairro X vende mais caro que o Centro).", max_length=80),
        ),
    ]
