# Generated by Django 6.1.1 on 2026-09-16 14:12

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('captacao', '0003_precocaptado_bairro'),
        ('lojas', '0003_loja_ativa'),
    ]

    operations = [
        migrations.CreateModel(
            name='PrecoHistorico',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('data', models.DateField(db_index=True)),
                ('ean', models.CharField(db_index=True, max_length=20)),
                ('cidade_busca', models.CharField(blank=True, db_index=True, max_length=60)),
                ('tipo', models.CharField(blank=True, max_length=20)),
                ('rede_nome', models.CharField(blank=True, max_length=60)),
                ('estabelecimento', models.CharField(blank=True, max_length=200)),
                ('endereco', models.CharField(blank=True, max_length=300)),
                ('preco', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('loja', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='precos_historico', to='lojas.loja')),
            ],
            options={
                'verbose_name': 'Preço histórico',
                'verbose_name_plural': 'Preços históricos',
                'indexes': [models.Index(fields=['ean', 'cidade_busca', 'data'], name='captacao_pr_ean_3aae3e_idx')],
                'constraints': [models.UniqueConstraint(fields=('data', 'ean', 'estabelecimento', 'endereco'), name='uniq_preco_historico')],
            },
        ),
    ]
