# Generated by Django 6.1.1 on 2026-09-16 17:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('captacao', '0004_precohistorico'),
    ]

    operations = [
        migrations.AddField(
            model_name='rede',
            name='ativa',
            field=models.BooleanField(default=True, help_text="Só Redes tipo=concorrente ATIVAS entram no Monitor de Preço. Gabriel pediu (16/09/26) pra ver TODO concorrente captado (não só os 6 curados originais) e escolher quem conta -- concorrentes descobertos automaticamente ('manage.py descobrir_concorrentes') entram como inativos por padrão, pra ele revisar antes de contarem na comparação."),
        ),
        migrations.AlterField(
            model_name='rede',
            name='nome',
            field=models.CharField(max_length=200, unique=True),
        ),
    ]
